In [1]:
import numpy as np

In [2]:
image = np.array([[[10, 20, 30], [11, 21, 31], [12, 22, 32]], [[40, 50, 60], [41, 51, 61], [42, 52, 62]], [[7, 8, 9], [17, 18, 19], [27, 28, 29]]])
kernel = np.array([[1, 2, 1], [2, 4, 2], [1, 2, 1]])
i = 1
j = 1
# matrix = image[i-1:i+2, j-1:j+2,:]
# blur = np.array(image)
# for i in range(1, image.shape[0]-1):
#     for j in range(1, image.shape[1]-1):
#         blur[i][j] = np.sum(image[i-1:i+2, j-1:j+2,:] * kernel[:, :, None], axis=(0, 1))

# # print(matrix)
# # print(np.sum(matrix, axis=0))
# print(matrix * kernel[:, :, None])
# sum = np.sum(matrix * kernel[:, :, None], axis=(0, 1))
print(image[:, :, 0])

[[10 11 12]
 [40 41 42]
 [ 7 17 27]]


In [3]:
image = np.array(range(1, 28)).reshape(3, 3, 3)
y ,x = np.ogrid[:512, :512]
print(image)
print(y.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(512, 1)


In [8]:
coeff = [4, 0, 0]
print(np.roots(coeff))


[0. 0.]
